apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    path: workloads/prometheus-operator
    repoURL: git@github.com:soal-one/soal-one-bootstrap
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus-operator
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
